# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dario Gartmann
email: hello@dariogartmann.ch
description: > # this means to ignore newlines until "baseurl:"
  I'm Dario Gartmann. A web designer, photographer and filmmaker based in Switzerland.
  This portfolio showcases some of my work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dario.works" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dario_gartmann
github_username:  dariogartmann

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: true

permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
